name: Test
on: push

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Install Lua
        uses: leafo/gh-actions-lua@master
        with:
          luaVersion: 5.1
      - name: Run test case
        run: lua ./tests.lua --Linux --CI
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test Linux
          conclusion: ${{ job.status }}
  
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Download Lua5.1
        run: curl -o Lua51.zip "https://raw.githubusercontent.com/joedf/LuaBuilds/gh-pages/hdata/lua-5.1.5_Win32_bin.zip"
      - name: Unzip Lua51
        run: |
          tar -xf Lua51.zip
      - name: Run test case
        run: ./lua.exe ./tests.lua --CI
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test Windows
          conclusion: ${{ job.status }}
